#pragma once

#define SKY_DIFFUSE_SAMPLER_UNIFORM_LOCATION "textureSampler"
#define TEXTURE_DIFFUSE_SAMPLER_UNIFORM_LOCATION "textureSampler"
#define SOLID_DIFFUSE_COLOR_UNIFORM_LOCATION "materialColor"
//#define LIGHT_POS_UNIFORM_LOCATION "lightPos"
